# Generated by Django 5.2.14 on 2026-06-01 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('category', models.CharField(choices=[('LIGHT', 'LED Lights'), ('STAND', 'Monitor Stands / Arms'), ('DESK', 'Smart / Ergonomic Desks'), ('CHAIR', 'Ergonomic Chairs'), ('PAD', 'Mousepads')], default='DESK', max_length=10, verbose_name='Danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá cơ bản')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Số lượng trong kho')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link ảnh sản phẩm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100, verbose_name='Loại tùy biến')),
                ('value', models.CharField(max_length=100, verbose_name='Giá trị tùy biến')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Giá cộng thêm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product', verbose_name='Sản phẩm chính')),
            ],
        ),
    ]
